mybatis:
  mapper-locations: classpath:/mybatis-mapper-postgresql/*Mapper.xml
server:
  context-path: /xxl-job-admin
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 30
      max-wait: 10000
      test-on-borrow: true
      validation-interval: 30000
      validation-query: SELECT 1
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://${DB_SERVER_IP}:${DB_SERVER_PORT}/${DB_NAME}?currentSchema=xxl_job
    username: ${DB_USERNAME}
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    host: ${MAIL_SERVER_HOST:smtp.qq.com}
    password: ${MAIL_PASSWORD:xxx}
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: ${MAIL_USERNAME:xxx@qq.com}
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
xxl:
  job:
    accessToken: ''
    i18n: ''
